"""add is_finalized to pdf

Revision ID: 84ee6f6f6344
Revises: 0fa6ecb898d1
Create Date: 2026-04-17 15:27:40.414532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84ee6f6f6344'
down_revision: Union[str, Sequence[str], None] = '0fa6ecb898d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfs', sa.Column('is_finalized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pdfs', 'is_finalized')
    # ### end Alembic commands ###
